apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petstore-resources
  namespace: openshift-operators
spec:
  project: default
  source:
    repoURL: 'https://github.com/carlesarnal/api-resources.git'
    targetRevision: main
    path: ./
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petstore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5