apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuadrant-clusterrole
rules:
- apiGroups: ["kuadrant.io"]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]