apiVersion: batch/v1
kind: Job
metadata:
  name: kuadrant-cli-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: kuadrant-cli
          image: bitnami/ubuntu:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Update and install required tools
              apt-get update && \
              apt-get install -y git curl && \
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
              chmod +x ./kubectl && mv ./kubectl /usr/local/bin/

              # Install kuadrantctl
              curl -Lo /usr/local/bin/kuadrantctl https://github.com/Kuadrant/kuadrantctl/releases/latest/download/kuadrantctl-linux-amd64 && \
              chmod +x /usr/local/bin/kuadrantctl

              # Create a writable directory for Git cloning
              mkdir -p /api-resources && chmod 777 /api-resources

              
              # Clone the repository
              git clone https://github.com/carlesarnal/api-resources.git /api-resources
              
              for file in /api-resources/*.yaml; do
                kuadrantctl generate gatewayapi httproute --oas "$file" | kubectl apply -f -
                kuadrantctl generate kuadrant --oas "$file" | kubectl apply -f -
                kuadrantctl generate kuadrant --oas "$file" | kubectl apply -f -
              done
          volumeMounts:
            - name: api-resources
              mountPath: /api-resources
      restartPolicy: Never
      volumes:
        - name: api-resources
          emptyDir: {}