kind: ApicurioRegistry3
apiVersion: registry.apicur.io/v1
metadata:
  name: apicurio-registry-deployment
  namespace: api-controller
  labels:
    app: apicurio-registry-sql
spec:
  app:
    host: apicurio-registry-api-controller.apps.controller.apicurio.integration-qe.com
    sql:
      dataSource:
        username: apicurio
        password: registry
        url: 'jdbc:postgresql://postgresql-service:5432/registry'
  studioUi:
    enabled: true
    host: apicurio-studio-api-controller.apps.controller.apicurio.integration-qe.com
  ui:
    host: apicurio-registry-ui-api-controller.apps.controller.apicurio.integration-qe.com