---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: apicurio-registry-ui-template
  namespace: api-controller
parameters:
  - name: REGISTRY_API_URL
    description: "The URL for the Apicurio Registry API"
    required: true
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: apicurio-registry-ui
      namespace: api-controller
      labels:
        app: apicurio-registry
        component: apicurio-registry-ui
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: apicurio-registry-ui
      template:
        metadata:
          labels:
            app: apicurio-registry
            component: apicurio-registry-ui
        spec:
          containers:
            - name: apicurio-registry-ui
              image: quay.io/apicurio/apicurio-registry-ui:latest-release
              ports:
                - name: web
                  containerPort: 8080
                  protocol: TCP
              env:
                - name: REGISTRY_API_URL
                  value: "${REGISTRY_API_URL}"
              livenessProbe:
                httpGet:
                  path: /config.js
                  port: 8080
                initialDelaySeconds: 10
              readinessProbe:
                httpGet:
                  path: /config.js
                  port: 8080
                initialDelaySeconds: 10
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: api-controller
      labels:
        app: apicurio-registry
        template: apicurio-registry-ui
      name: apicurio-registry-ui
    spec:
      selector:
        component: apicurio-registry-ui
      ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: web # referring to target port via "name" instead that via the number
      sessionAffinity: None
    status:
      loadBalancer: { }
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      namespace: api-controller
      name: apicurio-registry-ui
      labels:
        app: apicurio-registry
        template: apicurio-registry-ui
    spec:
      to:
        kind: Service
        name: apicurio-registry-ui
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None